#!/bin/bash

# Install nginx if not installed
apt-get update -y
apt-get install nginx -y

# Replace default page with "Hello World!"
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Start nginx using service command (not systemctl)
service nginx start
