#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response

# Update and install Nginx
apt-get -y update
apt-get -y install nginx

# Allow Nginx through the firewall
ufw allow 'Nginx HTTP'

# Set custom homepage
echo 'Holberton School' > /var/www/html/index.nginx-debian.html

# Add redirect and custom header to Nginx config
sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sed -i "/listen 80 default_server;/a add_header X-Served-By $(hostname);" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
